### ISSUE TITLE
API key mismatch

### ISSUE THREAD

**Issue by tarapitha** [ipzero209/GoldenGate#7]
I have practically no experience with the Pan-OS XML API, so please forgive me if my opinions are wildly off the mark.

I am not sure if it is the problem with the utility or with the latest Panorama version, but the utility will exit as soon as it tries to connect to one of the <8.0 version firewalls.

Using:
GoldenGate v1.3
Panorama  v9.0.4
Older firewalls v7.1.25 that run on PA2020 appliances

It seems that when shim_setup.py requests Panorama API keygen, then the key is returned different at every request. When the same API request is run for firewall that runs any version, then it returns consistently the same key for all firewalls. This key is not equal to the keys that are returned by the Panorama.

shim_setup.py stores the key that is received from Panorama into "data" file and the pan_shim.py uses the same key from the "data" file. As the key from Panorama will not match the ones for the firewalls, then the authentication fails for any XML API call for any firewall.

I think that it is possible to get it working by requesting the keygen not from the panorama, but from the first firewall that is returned by Panorama, but it will certainly be the ugly hack.

**Comment by ipzero209** [comment]
How API keys are generated has changed in PAN-OS v9.0, which is what is causing this issue. Running PAN-OS 8.1 on Panorama will still work. Because PAN-OS v7.1 is end of support at the end of March, I didn't have plans to update this tool. 

If you have a pressing need for this until 29 March, let me know and I can branch it and put together a release for you, time permitting.

**Comment by tarapitha** [comment]
Thank you! I got it working by doing the hack I proposed. There were couple of other issues, like 7.1 returning non-numerical log rate and power supply reply being non-parsable json, but I just commented the requests out. All our other firewalls are 8.1 or above and we are going to replace the remaining two EOL appliances during 2020 year.
